# `try-finally`보다는 `try-with-resources`를 사용하라

자바 라이브러리에는 `close` 메서드로 직접 닫아줘야 하는 자원이 많다. 

e.g. `InputStream`, `OutputStream`, `java.sql.Connection`

`close`을 하지 않는다면 예측하지 못한 성능 문제가 발생할 수 있다.

`finalizer`를 안전망으로 사용할 수 있지만, 믿을만하지 못하다!

<br> 

### `try-finally`

* 자원이 제대로 닫힘을 보장해주는 전통적 수단이다.
* `try-finally` 예시 코드
  ```java
  // 코드 9-1
  // try-finally: 더 이상 자원을 회수하는 최선의 방안이 아니다!
  static String firstLineOfFile(String path) throws IOExeption {
      BufferedReader br = new BufferedREader(new FileReader(path));
      try {
          return br.readLine();
      } finally {
          br.close();
      }
  }
  ```
  * `readLine()`과 `close()` 호출 양쪽에서 발생하면, `close`에서 발생한 예외는 `readLine()`로 인해 발생하는 예외로 감춰지게 된다.
    * 모든 예외를 보이게 코드를 수정할 수 있지만, 코드가 복잡해질 수 있다.
* 자원이 둘 이상일 때, `try-finally` 예시 코드
  ```java
  // 자원이 둘 이상일 때, try-finally 방식은 지저분하다!
  static String copy(String src, String dst) throws IOExeption {
      InputSTream in = new FileInputStream(src);
      try {
          OutputStream out = new FileOutputStream(dst);
          try {
              byte[] buf = new byte[BUFFER_SIZE];
              int n;
              while((n = in.read(buf)) >= 0) 
                  out.write(buf, 0, n);
          } finally {
              out.close;
          } finally {
              in.close();
          }
      }
  }
  ```
  * 자원이 한 개만 추가되었는데도, 코드가 복잡해진 것을 확인할 수 있다.
* `try-finally` 방식의 문제점
  * 여러 개의 에러가 발생되도 예외 하나만 보존되고, 여러 개의 다른 예외가 숨겨질 수 있다.
  * 자원이 둘 이상일 경우에는 코드가 복잡해진다.

<br>

### `try-with-resource`

* `try-finally`를 사용했을 때 발생하는 문제를 해결해준다.
* `try-with-resource`를 사용하기 위해서는 해당 자원이 `AutoCloseable`인터페이스를 구현해야 된다.
  * 단순히 `void`를 반환하는 `close`메서드 하나만 정의한 인터페이스
```java
// try-with-resource를 사용해 9-1 재작성
// try-with-resource: 자원을 회수하는 최선책!
static String firstLineOfFile(String path) throws IOException {
    try(BufferedReader br = new BufferedReader(new FileReader(path))) {
        return br.readLine();
    }
}
```
```java
// try-widh-resource를 사용해 9-2 재작성
// 복수의 자원을 처리하는 try-with-resource
static void copy(String src, String dst) throws IOException {
    try(InputSTream in = new FileInputStream(src);
       OutputStream out = new FileOutputStream(dst)) {
        byte[] buf = new byte[BUFFER_SIZE];
        int n;
        while((n = in.read(buf)) >= 0)
            out.write(buf, 0, n);
    }
} 
```

<br>



### `try-with-resource-catch`

* `catch`문을 사용해서 `try`문을 중첩하지 않고도 다수의 예외를 처리할 수 있다.
```java
// try-with-resources를 catch절과 사용
// 데이터를 읽지 못했을 때, 예외를 던지는 대신 기본값을 반환하는 예제
static String firstLineOfFile(String path, String defaultVal) {
    try(BufferedReader br = new BufferedReader(new FileReader(path))) {
        return br.readLine();
    } catch(IOException e) {
        return defaultVal;
    }
}
```
<br>



### 정리

* 꼭 회수해야 하는 자원은 `try-finally`가 아닌,  `try-with-resource`를 사용하자!
* `try-with-resource`를 사용하면 코드는 더 짧아지고, 만들어지는 예외 정보도 유용하다!
* `try-with-resource`는 `try-finally`에 비해 정확하고 쉽게 자원을 회수할 수 있다!